version: '3'
services:

  ###############################
  cassandra0:
    image: cassandra:3.11.1
    container_name: cassandra
    ports:
    - 9042:9042
    - 9160:9160
    - 7199:7199
    - 8778:8778
    environment:
    - CASSANDRA_START_RPC=true
    - CASSANDRA_SEEDS=cassandra
    - CASSANDRA_CLUSTER_NAME=mtech_cluster
    volumes:
    - "./cassandra-init.sh:/cassandra-init.sh"
    command: "sh /cassandra-init.sh"
    ulimits:
      memlock: -1
      nproc: 32768
      nofile: 100000
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]

  ##############################
  grafana:
    image: grafana/grafana:master
    container_name: grafana
    ports:
    - 3000:3000

  ##############################
  portainer:
    container_name: portainer
    image: portainer/portainer
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - 9000:9000